import { NetworkLayer, Sem2Project } from "../types";

export function getProjectLayers(project: Sem2Project, customConfig?: { batchSize?: number }): NetworkLayer[] {
  const batch = customConfig?.batchSize || 32;
  const numFeatures = project.features?.length || 5;

  if (project.layers && project.layers.length > 0) {
    return project.layers;
  }

  // Pre-configured architectures for our curated Sem-2 models
  if (project.id === "stochastic-pathfinding" || project.name.includes("Pathfinding")) {
    return [
      {
        id: "l0_grid_state",
        name: "Grid_State_Tensor",
        type: "Spatial Input Tensor",
        shape: `[${batch}, 4, 16, 16]`,
        units: 16 * 16,
        activation: "None",
        weightsCount: 0,
        biasesCount: 0,
        totalParams: 0,
        trainable: false,
        description: "4-channel spatial state map: Ch0=Agent Position, Ch1=Goal Coordinate, Ch2=Static Barriers, Ch3=Hazard Threat",
        formula: "s_t ∈ ℝ^{B × 4 × 16 × 16}",
        outputSummary: "Normalized multi-channel grid occupancy matrix",
      },
      {
        id: "l1_spatial_conv",
        name: "Spatial_Conv2D",
        type: "2D Convolution",
        shape: `[${batch}, 32, 16, 16]`,
        units: 32,
        activation: "LeakyReLU",
        weightsCount: 4 * 32 * 3 * 3,
        biasesCount: 32,
        totalParams: 4 * 32 * 3 * 3 + 32,
        trainable: true,
        description: "Extracts local spatial topology, corner traps, obstacle clearances, and hazard gradient contours",
        formula: "C₁ = LeakyReLU(W_{conv} * s_t + b)",
        outputSummary: "32 feature maps encoding local barrier clearances",
      },
      {
        id: "l2_residual_block",
        name: "Residual_Bottleneck",
        type: "Residual Conv2D Block",
        shape: `[${batch}, 32, 16, 16]`,
        units: 32,
        activation: "ReLU",
        weightsCount: 32 * 32 * 3 * 3,
        biasesCount: 32,
        totalParams: 32 * 32 * 3 * 3 + 32,
        trainable: true,
        description: "Identity shortcut skip connection preserving geometric coordinate fidelity across path layers",
        formula: "R = ReLU(W₂ * C₁ + C₁)",
        outputSummary: "Skip-connected topological representation",
      },
      {
        id: "l3_latent_dense",
        name: "Dense_Stochastic_Latent",
        type: "Dense Linear",
        shape: `[${batch}, 128]`,
        units: 128,
        activation: "ELU",
        weightsCount: 32 * 16 * 16 * 128,
        biasesCount: 128,
        totalParams: 32 * 16 * 16 * 128 + 128,
        trainable: true,
        description: "Flattens spatial features into high-dimensional transition belief vectors conditioned on slip variance ε",
        formula: "z = ELU(W_z · vec(R) + b_z)",
        outputSummary: "128-dim latent policy embedding",
      },
      {
        id: "l4_value_stream",
        name: "Dueling_State_Value_V(s)",
        type: "Value Stream",
        shape: `[${batch}, 1]`,
        units: 1,
        activation: "Linear",
        weightsCount: 128 * 1,
        biasesCount: 1,
        totalParams: 129,
        trainable: true,
        description: "Scalar state-value estimator computing expected discounted Bellman return V(s) regardless of action taken",
        formula: "V(s) = W_v · z + b_v",
        outputSummary: "Scalar Bellman expected state utility",
      },
      {
        id: "l5_q_actions",
        name: "Stochastic_Q_Head",
        type: "Dueling Q-Action Head",
        shape: `[${batch}, 4]`,
        units: 4,
        activation: "Softmax / Q-Policy",
        weightsCount: 128 * 4,
        biasesCount: 4,
        totalParams: 128 * 4 + 4,
        trainable: true,
        description: "Dueling aggregation Q(s,a) = V(s) + [A(s,a) - mean(A)] across 4 actions: {North, South, East, West} under slip ε",
        formula: "Q(s, a) = V(s) + (A(s, a) - 1/|A| ∑ A(s, a'))",
        outputSummary: "Stochastic directional Q-value expectation array",
      },
    ];
  }

  if (project.id === "student-performance") {
    return [
      {
        id: "l0_input",
        name: "Input_Stream",
        type: "Input Tensor",
        shape: `[${batch}, ${numFeatures}]`,
        units: numFeatures,
        activation: "None",
        weightsCount: 0,
        biasesCount: 0,
        totalParams: 0,
        trainable: false,
        description: "6 engineered academic signals (attendance, internal marks, GPA, study hours, assignments)",
        formula: "x ∈ ℝ⁶",
        outputSummary: "Normalized feature vector",
      },
      {
        id: "l1_dense",
        name: "Dense_Hidden_1",
        type: "Dense Linear",
        shape: `[${batch}, 64]`,
        units: 64,
        activation: "ReLU",
        weightsCount: numFeatures * 64,
        biasesCount: 64,
        totalParams: numFeatures * 64 + 64,
        trainable: true,
        description: "First hidden projection capturing non-linear study/attendance synergy",
        formula: "h₁ = ReLU(W₁ · x + b₁)",
        outputSummary: "64 feature embeddings",
      },
      {
        id: "l2_batchnorm",
        name: "BatchNorm_1",
        type: "Batch Normalization",
        shape: `[${batch}, 64]`,
        units: 64,
        activation: "None",
        weightsCount: 64,
        biasesCount: 64,
        totalParams: 128,
        trainable: true,
        description: "Standardizes hidden activations across mini-batches to prevent internal covariate shift",
        formula: "y = γ · ((x - μ) / √(σ² + ε)) + β",
        outputSummary: "Covariance stabilized tensor",
      },
      {
        id: "l3_dense",
        name: "Dense_Hidden_2",
        type: "Dense Bottleneck",
        shape: `[${batch}, 32]`,
        units: 32,
        activation: "ReLU",
        weightsCount: 64 * 32,
        biasesCount: 32,
        totalParams: 64 * 32 + 32,
        trainable: true,
        description: "Low-dimensional latent risk representation bottleneck",
        formula: "h₂ = ReLU(W₂ · h₁ + b₂)",
        outputSummary: "32 distilled risk latent features",
      },
      {
        id: "l4_output",
        name: "Softmax_Risk_Head",
        type: "Softmax Classifier",
        shape: `[${batch}, 3]`,
        units: 3,
        activation: "Softmax",
        weightsCount: 32 * 3,
        biasesCount: 3,
        totalParams: 32 * 3 + 3,
        trainable: true,
        description: "Probability distribution over [Low Risk, Moderate Risk, Critical Dropout]",
        formula: "P(y = k) = e^{z_k} / ∑ e^{z_j}",
        outputSummary: "Tri-class probability distribution",
      },
    ];
  }

  if (project.id === "smart-attendance") {
    return [
      {
        id: "l0_input",
        name: "Input_Tensor",
        type: "Image Tensor",
        shape: `[${batch}, 3, 112, 112]`,
        units: 112,
        activation: "None",
        weightsCount: 0,
        biasesCount: 0,
        totalParams: 0,
        trainable: false,
        description: "Aligned and cropped facial RGB patch from camera feed",
        formula: "X ∈ ℝ^{B × 3 × 112 × 112}",
        outputSummary: "Preprocessed RGB spatial frame",
      },
      {
        id: "l1_conv",
        name: "Conv2D_Stem",
        type: "Convolutional",
        shape: `[${batch}, 32, 56, 56]`,
        units: 32,
        activation: "ReLU6",
        weightsCount: 3 * 3 * 3 * 32,
        biasesCount: 32,
        totalParams: 3 * 3 * 3 * 32 + 32,
        trainable: true,
        description: "3x3 convolution stride 2 extracting edges, ocular regions, and contours",
        formula: "F₁ = ReLU6(W * X + b)",
        outputSummary: "32 feature maps (56×56)",
      },
      {
        id: "l2_bottleneck",
        name: "Inverted_Residual",
        type: "Depthwise Separable",
        shape: `[${batch}, 64, 28, 28]`,
        units: 64,
        activation: "ReLU6",
        weightsCount: 18432,
        biasesCount: 64,
        totalParams: 18496,
        trainable: true,
        description: "MobileNetV2 linear bottleneck with expansion factor t=6",
        formula: "F₂ = ResBlock(F₁) + F₁",
        outputSummary: "64 feature maps (28×28)",
      },
      {
        id: "l3_pool",
        name: "Global_Avg_Pool",
        type: "Spatial Reduction",
        shape: `[${batch}, 128]`,
        units: 128,
        activation: "None",
        weightsCount: 0,
        biasesCount: 0,
        totalParams: 0,
        trainable: false,
        description: "Condenses 2D spatial dimensions into 1D spatial descriptor vector",
        formula: "v = 1/(H×W) ∑∑ F₂(i,j)",
        outputSummary: "Flattened latent vector",
      },
      {
        id: "l4_dense",
        name: "FaceNet_Embedding",
        type: "Dense Embedding",
        shape: `[${batch}, 128]`,
        units: 128,
        activation: "Linear",
        weightsCount: 128 * 128,
        biasesCount: 128,
        totalParams: 128 * 128 + 128,
        trainable: true,
        description: "128-dimensional unit hypersphere vector with L2 normalization for cosine matching",
        formula: "e = (W · v + b) / ‖W · v + b‖₂",
        outputSummary: "128-D Euclidean invariant face embedding",
      },
      {
        id: "l5_svm",
        name: "Margin_Classifier",
        type: "Decision Head",
        shape: `[${batch}, 1]`,
        units: 1,
        activation: "Sigmoid",
        weightsCount: 128 * 1,
        biasesCount: 1,
        totalParams: 129,
        trainable: true,
        description: "RBF margin / Sigmoid match confidence score compared against biometric threshold",
        formula: "Score = σ(wᵀ e - θ)",
        outputSummary: "Identity match probability [0.0 - 1.0]",
      },
    ];
  }

  if (project.id === "healthcare-diagnosis") {
    return [
      {
        id: "l0_input",
        name: "Clinical_Vitals_Input",
        type: "Input Vector",
        shape: `[${batch}, ${numFeatures}]`,
        units: numFeatures,
        activation: "None",
        weightsCount: 0,
        biasesCount: 0,
        totalParams: 0,
        trainable: false,
        description: "Standardized physiological features: body temp, bpm, SpO2, duration, symptom code",
        formula: "x ∈ ℝ⁵",
        outputSummary: "Normalized clinical intake tensor",
      },
      {
        id: "l1_dense",
        name: "Dense_Perceptron_1",
        type: "Dense Layer",
        shape: `[${batch}, 128]`,
        units: 128,
        activation: "LeakyReLU",
        weightsCount: numFeatures * 128,
        biasesCount: 128,
        totalParams: numFeatures * 128 + 128,
        trainable: true,
        description: "Dense representation layer with non-zero slope (α=0.01) to prevent dying units",
        formula: "h₁ = LeakyReLU(W₁ x + b₁)",
        outputSummary: "128 clinical embedding units",
      },
      {
        id: "l2_bn",
        name: "BatchNorm_Layer",
        type: "Batch Normalization",
        shape: `[${batch}, 128]`,
        units: 128,
        activation: "None",
        weightsCount: 128,
        biasesCount: 128,
        totalParams: 256,
        trainable: true,
        description: "Maintains zero-mean unit variance across fluctuating patient vitals",
        formula: "y = γ x̂ + β",
        outputSummary: "Normalized hidden tensor",
      },
      {
        id: "l3_dense",
        name: "Dense_Perceptron_2",
        type: "Dense Layer",
        shape: `[${batch}, 64]`,
        units: 64,
        activation: "LeakyReLU",
        weightsCount: 128 * 64,
        biasesCount: 64,
        totalParams: 128 * 64 + 64,
        trainable: true,
        description: "Synergistic cross-symptom pathology distillation",
        formula: "h₂ = LeakyReLU(W₂ h₁ + b₂)",
        outputSummary: "64 distilled diagnostic features",
      },
      {
        id: "l4_output",
        name: "Triage_Softmax_Head",
        type: "Softmax Classifier",
        shape: `[${batch}, 5]`,
        units: 5,
        activation: "Softmax",
        weightsCount: 64 * 5,
        biasesCount: 5,
        totalParams: 64 * 5 + 5,
        trainable: true,
        description: "Clinical urgency probabilities over 5 categories (Normal, Low, Moderate, High, Emergency)",
        formula: "P(c) = e^{z_c} / ∑ e^{z_j}",
        outputSummary: "Urgency classification vector",
      },
    ];
  }

  if (project.id === "resume-screener") {
    return [
      {
        id: "l0_input",
        name: "Token_Input_Stream",
        type: "Token Sequence",
        shape: `[${batch}, 128]`,
        units: 128,
        activation: "None",
        weightsCount: 0,
        biasesCount: 0,
        totalParams: 0,
        trainable: false,
        description: "Byte-Pair tokenized resume vocabulary ids and attention masks",
        formula: "T ∈ ℤ^{B × 128}",
        outputSummary: "128 token indices",
      },
      {
        id: "l1_attention",
        name: "MultiHead_Attention",
        type: "Self-Attention",
        shape: `[${batch}, 128, 256]`,
        units: 256,
        activation: "GELU",
        weightsCount: 196608,
        biasesCount: 0,
        totalParams: 196608,
        trainable: true,
        description: "8 attention heads learning contextual keyword equivalence and semantic skill relevance",
        formula: "Attn = Softmax((Q · Kᵀ) / √d_k) · V",
        outputSummary: "Contextualized token embeddings",
      },
      {
        id: "l2_pool",
        name: "Mean_Token_Pooling",
        type: "Sequence Pooling",
        shape: `[${batch}, 256]`,
        units: 256,
        activation: "None",
        weightsCount: 0,
        biasesCount: 0,
        totalParams: 0,
        trainable: false,
        description: "Mean pooling across valid token masks for holistic document vectorization",
        formula: "u = (1 / L) ∑ h_t",
        outputSummary: "256-D resume semantic vector",
      },
      {
        id: "l3_dense",
        name: "Dense_Projection",
        type: "Dense Linear",
        shape: `[${batch}, 64]`,
        units: 64,
        activation: "GELU",
        weightsCount: 256 * 64,
        biasesCount: 64,
        totalParams: 256 * 64 + 64,
        trainable: true,
        description: "Projects semantic sentence vectors into recruitment criteria space",
        formula: "z = GELU(W · u + b)",
        outputSummary: "64 criteria match factors",
      },
      {
        id: "l4_output",
        name: "Match_Score_Head",
        type: "Regression Head",
        shape: `[${batch}, 1]`,
        units: 1,
        activation: "Sigmoid",
        weightsCount: 64 * 1,
        biasesCount: 1,
        totalParams: 65,
        trainable: true,
        description: "Normalized semantic match ratio between resume and target job profile",
        formula: "Score = σ(wᵀ z + b)",
        outputSummary: "Fit percentage [0.0% - 100.0%]",
      },
    ];
  }

  // Dynamic procedural layer synthesis for any custom user project:
  const hidden1 = Math.max(32, numFeatures * 8);
  const hidden2 = Math.max(16, Math.floor(hidden1 / 2));
  const outputUnits = project.domain.toLowerCase().includes("regression") ? 1 : 3;
  const outputAct = outputUnits === 1 ? "Linear" : "Softmax";

  return [
    {
      id: "l0_input",
      name: "Feature_Input_Stream",
      type: "Input Vector",
      shape: `[${batch}, ${numFeatures}]`,
      units: numFeatures,
      activation: "None",
      weightsCount: 0,
      biasesCount: 0,
      totalParams: 0,
      trainable: false,
      description: `${numFeatures} domain inputs parsed from input tensors`,
      formula: `x ∈ ℝ^{${numFeatures}}`,
      outputSummary: "Standardized input vector",
    },
    {
      id: "l1_dense",
      name: "Dense_Projection_1",
      type: "Dense Linear",
      shape: `[${batch}, ${hidden1}]`,
      units: hidden1,
      activation: "ReLU",
      weightsCount: numFeatures * hidden1,
      biasesCount: hidden1,
      totalParams: numFeatures * hidden1 + hidden1,
      trainable: true,
      description: `Primary hidden projection matrix (${numFeatures} ➔ ${hidden1})`,
      formula: "h₁ = ReLU(W₁ · x + b₁)",
      outputSummary: `${hidden1} latent feature representations`,
    },
    {
      id: "l2_bn",
      name: "BatchNorm_Layer",
      type: "Batch Normalization",
      shape: `[${batch}, ${hidden1}]`,
      units: hidden1,
      activation: "None",
      weightsCount: hidden1,
      biasesCount: hidden1,
      totalParams: hidden1 * 2,
      trainable: true,
      description: "Normalizes distribution across mini-batches to accelerate convergence",
      formula: "y = γ x̂ + β",
      outputSummary: "Batch normalized hidden state",
    },
    {
      id: "l3_dense",
      name: "Dense_Bottleneck_2",
      type: "Dense Hidden",
      shape: `[${batch}, ${hidden2}]`,
      units: hidden2,
      activation: "ReLU",
      weightsCount: hidden1 * hidden2,
      biasesCount: hidden2,
      totalParams: hidden1 * hidden2 + hidden2,
      trainable: true,
      description: `Second hidden layer refining representations (${hidden1} ➔ ${hidden2})`,
      formula: "h₂ = ReLU(W₂ · h₁ + b₂)",
      outputSummary: `${hidden2} refined latent units`,
    },
    {
      id: "l4_output",
      name: "Inference_Output_Head",
      type: outputUnits === 1 ? "Regression Head" : "Softmax Classifier",
      shape: `[${batch}, ${outputUnits}]`,
      units: outputUnits,
      activation: outputAct,
      weightsCount: hidden2 * outputUnits,
      biasesCount: outputUnits,
      totalParams: hidden2 * outputUnits + outputUnits,
      trainable: true,
      description: `Final model prediction layer outputting ${outputUnits} decision target${outputUnits > 1 ? "s" : ""}`,
      formula: outputUnits === 1 ? "y = W · h₂ + b" : "P(y = k) = e^{z_k} / ∑ e^{z_j}",
      outputSummary: outputUnits === 1 ? "Scalar prediction value" : "Class probability distribution",
    },
  ];
}
